// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcncpi_w7usDXs_g2oaQr6AmnT0AQ8OEo',
    appId: '1:786612536106:web:d9246fd69a173ffb165453',
    messagingSenderId: '786612536106',
    projectId: 'ecommerce-efe64',
    authDomain: 'ecommerce-efe64.firebaseapp.com',
    storageBucket: 'ecommerce-efe64.firebasestorage.app',
    measurementId: 'G-JNPE7TBKHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbavkzwqumFy7k6W4mCFEQdoA_txKvGfA',
    appId: '1:786612536106:android:23f2a4ad4d43c799165453',
    messagingSenderId: '786612536106',
    projectId: 'ecommerce-efe64',
    storageBucket: 'ecommerce-efe64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZeStbx6295R359v6t7hDbYvlBWgTzPlo',
    appId: '1:786612536106:ios:ec8f90330b6ad09b165453',
    messagingSenderId: '786612536106',
    projectId: 'ecommerce-efe64',
    storageBucket: 'ecommerce-efe64.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationProyek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZeStbx6295R359v6t7hDbYvlBWgTzPlo',
    appId: '1:786612536106:ios:ec8f90330b6ad09b165453',
    messagingSenderId: '786612536106',
    projectId: 'ecommerce-efe64',
    storageBucket: 'ecommerce-efe64.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationProyek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcncpi_w7usDXs_g2oaQr6AmnT0AQ8OEo',
    appId: '1:786612536106:web:4971cebeabc4e65e165453',
    messagingSenderId: '786612536106',
    projectId: 'ecommerce-efe64',
    authDomain: 'ecommerce-efe64.firebaseapp.com',
    storageBucket: 'ecommerce-efe64.firebasestorage.app',
    measurementId: 'G-Z1WMTXZDNM',
  );
}
